COMPILER = g++
WARNING = -Wall
STANDARD = -std=c++14
DEBUG = -g
OPTIMIZATION = -O0
DIRECTORY = -I.
BASE = $(basename $(FILE))
FILE =
LINK =

# for building and manually testing
default:
	$(COMPILER) ${WARNING} ${STANDARD} ${DEBUG} ${DIRECTORY} ${FILE} ${LINK} -o ${BASE}
	./${BASE}

# builds test
test-build:
	make -C test all

# runs test
test-run:
	./test/String-spec

# cleans files generated by test
test-clean:
	make -C test clean
